mod waveform;
mod vu_meter;
mod transport;
mod deck_panel;
mod knob;
mod crossfader;
mod mixer;
mod tempo;
mod fx_rack;
mod spectrum;
mod scope;
mod phase;
mod library;
mod status_bar;
mod energy_bridge;

pub use deck_panel::DeckPanel;
pub use mixer::MixerPanel;
pub use spectrum::SpectrumWidget;
pub use scope::ScopeWidget;
pub use phase::PhaseWidget;
pub use library::LibraryPanel;
pub use status_bar::StatusBar;
pub use fx_rack::FxRack;
pub use energy_bridge::EnergyBridge;
